In [2]:
#These exercises were taken from: https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hints.md

In [3]:
import numpy as np

In [14]:
# 3. Create a null vector of size 10
a = np.zeros(10)

In [18]:
# 4. How to find the memory size of any array (★☆☆)
a = np.zeros((10,10))
print(a.size)
print(a.itemsize)
print("{} bytes".format(a.size*a.itemsize))

100
8
800 bytes


In [19]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [21]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
# Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
m = np.arange(0,9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
el = [1,2,0,0,4,0]
a = np.array(el)
nz = a.nonzero()
nz

(array([0, 1, 4], dtype=int64),)

In [34]:
# 11. Create a 3x3 identity matrix (★☆☆)
i = np.eye(3,3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
# 12. Create a 3x3x3 array with random values (★☆☆)
r = np.random.random((3,3,3))
r

array([[[0.84543638, 0.53117343, 0.40260057],
        [0.54226019, 0.1644495 , 0.10138484],
        [0.72900377, 0.70843372, 0.63983972]],

       [[0.91555277, 0.60994024, 0.03842449],
        [0.70994845, 0.34311037, 0.75347228],
        [0.87227645, 0.21491865, 0.52748616]],

       [[0.1065797 , 0.68533588, 0.30919406],
        [0.6940671 , 0.87316937, 0.12785882],
        [0.64492746, 0.33005098, 0.59125377]]])

In [56]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
s = np.random.random((10,10))
print(s)
print(f"Max value: {s.max()} is on {s.argmax()}")
print(f"Min value: {s.min()} is on {s.argmin()}")

[[0.67894745 0.12210987 0.7649577  0.79408066 0.80064953 0.33245018
  0.38684857 0.41385781 0.42004248 0.88243192]
 [0.72090408 0.26848121 0.54898141 0.57383676 0.0329462  0.00696893
  0.77637107 0.86232196 0.27866736 0.19808179]
 [0.94484037 0.01832079 0.96514825 0.47619673 0.55519687 0.69124341
  0.802528   0.43345283 0.58492413 0.49888221]
 [0.62387482 0.25709712 0.86178221 0.19044606 0.09630313 0.60775005
  0.05221014 0.18363566 0.97980203 0.53007943]
 [0.47546651 0.01905008 0.43386448 0.11550813 0.97927038 0.79526091
  0.55461762 0.33119718 0.6122217  0.3825644 ]
 [0.44562315 0.54675014 0.73334991 0.11858824 0.30005404 0.27703251
  0.60439946 0.6681532  0.03379876 0.83499925]
 [0.87975028 0.083987   0.0449445  0.45197653 0.86969643 0.7928223
  0.03310208 0.49239614 0.98365724 0.54754285]
 [0.96842807 0.46329117 0.68708101 0.71876112 0.05618155 0.78075841
  0.63168426 0.2684403  0.61902342 0.04596913]
 [0.38485868 0.70825523 0.14883146 0.85474175 0.50033752 0.25755031
  0.83978333 

In [68]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
e = np.ones((10,10))
e[1:len(e)-1,1:len(e)-1] = 0
e

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [75]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
z = np.ones((5,5))
z = np.pad(z,pad_width=1, mode='constant', constant_values=0)
print(z)
print("\n")
x = np.ones((5,5))
x[:, [0, -1]] = 0
x[[0, -1], :] = 0
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [88]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
a = np.diag([1,2,3,4],k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [94]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [100]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
# r = np.random.random((6,7,8))
r = np.unravel_index(100,(6,7,8))
r

(1, 5, 4)

In [102]:
# 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [106]:
a = np.tile(np.array((0,1)),(2,3)) #Repete x vezes na (linha,coluna)
a

array([[0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1]])

In [109]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [110]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
